### PR TITLE
Add BabyCube 3D Printer

### PR DESCRIPTION
**Pull request by t-paul**

### CODE REVIEW

**Review by solidboredom — APPROVED** [review]

**Comment by martinbudden** [comment]
@t-paul , I just noticed this. Can I ask what this list is used for? I thought it might be for the OpenSCAD gallery, https://openscad.org/gallery.html, but BabyCube does not appear there.

**Comment by t-paul** [comment]
It's meant to be used for the gallery page eventually, but still needs work on the actual website to use this data.

**Comment by t-paul** [comment]
Ah, the gallery part was easy to convert, so it's live now, including the BabyCube :tada:. The news will need more changes as there's no place for a newsticker on the page yet.

**Comment by martinbudden** [comment]
Great to see BabyCube in the gallery, thanks.

**Pull request merged**
