### PR TITLE
Add VW Beetle again

### PR DESCRIPTION
**Pull request by t-paul**

### CODE REVIEW

**Review by UBaer21 — APPROVED** [review]
site checked, image checked.

**Review by UBaer21 — CHANGES_REQUESTED** [review]
seems there is a different image on the website for it
http://www.commandermodel.com/articles/projects/Beetle.prototype.2/openscad_exploded_view.png

**Review by UBaer21 — APPROVED** [review]

**Review by rcolyer — APPROVED** [review]

**Comment by solidboredom** [comment]
Thorsten, really  sorry for spamming here, i find no other way to contact you, could you add the constructive lib to the Library list? i have lost your email. very happy to see this deleted after read. Peter

**Comment by t-paul** [comment]
Makes sense, I'll move it to the library list, it certainly fits all the critera (open source + good documentation). And I can use the removal in the gallery for another try with auto-merge :grinning:.

For reaching out, you can also use the IRC channel (link on the homepage in the news ticker on top).

**Comment by t-paul** [comment]
Added to the library list. Just asking... is it intentionally GPL-2.0-**only**? It's totally fine if that's the case, it makes it incompatible with any GPL-3.0 code though.

**Pull request merged**
